version: "3.7"
services:
  jenkins:
    container_name: jenkins
    image: ericnaglertw/cd4ml-build-master:2
    ports:
      - "10000:8080"
    environment:
        FLUENTD_HOST: fluentd
        FLUENTD_PORT: 24224
        TENANT: "jenkins"
    volumes:
      - jenkins_home:/var/jenkins_home
    secrets:
      - jenkins-admin-password
    networks:
      - jenkins_nw

  mlflow:
    container_name: mlflow
    image: ericnaglertw/cd4ml-mlflow:1
    ports:
      - "12000:5000"
    networks:
      - jenkins_nw
  
#  dev:
#    container_name: dev
#    image: jupyter/minimal-notebook:latest
#    environment:
#      - JUPYTER_ENABLE_LAB=yes
#    ports:
#      - "8888:8888"
#      - "8889:8888"
#    volumes:
#      - .:/home/jovyan/
#    networks:
#      - jenkins_nw
#    depends_on:
#      - jenkins

volumes:
  jenkins_home:
    driver: local
  data01:
    driver: local

networks:
  jenkins_nw:
    driver: bridge

secrets:
  jenkins-admin-password:
    file: ../jenkins/jenkins-admin-password.txt